import { Badge } from "@/components/ui/badge"

export default function TermsPage() {
    return (
        <div className="max-w-4xl mx-auto px-4 py-8">
            <div className="mb-8">
                <Badge variant="secondary" className="bg-blue-600/20 text-blue-400 border-blue-600/30 mb-4">
                    Legal
                </Badge>
                <h1 className="text-4xl font-bold text-white dark:text-white light:text-slate-900 mb-4">Terms of Service</h1>
                <p className="text-slate-400 dark:text-slate-400 light:text-slate-600">Last updated: December 2024</p>
            </div>

            <div className="prose prose-slate dark:prose-invert light:prose-slate max-w-none">
                <div className="space-y-8">
                    <section>
                        <h2 className="text-2xl font-bold text-white dark:text-white light:text-slate-900 mb-4">
                            Acceptance of Terms
                        </h2>
                        <p className="text-slate-300 dark:text-slate-300 light:text-slate-700">
                            By using Freakend CLI, you agree to these terms of service. If you do not agree, please do not use our
                            software.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white dark:text-white light:text-slate-900 mb-4">License</h2>
                        <p className="text-slate-300 dark:text-slate-300 light:text-slate-700 mb-4">
                            Freakend CLI is open-source software licensed under the MIT License. You are free to:
                        </p>
                        <ul className="list-disc list-inside text-slate-300 dark:text-slate-300 light:text-slate-700 space-y-2 ml-4">
                            <li>Use the software for personal and commercial projects</li>
                            <li>Modify and distribute the software</li>
                            <li>Include it in proprietary software</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white dark:text-white light:text-slate-900 mb-4">Generated Code</h2>
                        <p className="text-slate-300 dark:text-slate-300 light:text-slate-700">
                            Code generated by Freakend CLI belongs to you. You have full ownership and rights to use, modify, and
                            distribute the generated code without any restrictions.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white dark:text-white light:text-slate-900 mb-4">Disclaimer</h2>
                        <p className="text-slate-300 dark:text-slate-300 light:text-slate-700">
                            Freakend CLI is provided "as is" without warranty of any kind. We are not liable for any damages arising
                            from the use of this software.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white dark:text-white light:text-slate-900 mb-4">Contact</h2>
                        <p className="text-slate-300 dark:text-slate-300 light:text-slate-700">
                            For questions about these terms, contact us at{" "}
                            <a href="mailto:legal@freakend.dev" className="text-blue-400 hover:text-blue-300">
                                legal@freakend.dev
                            </a>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    )
}
